const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_CART_ITEMS: "ADD_CART_ITEMS",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  DECREASE_ITEM_QTY: "DECREASE_ITEM_QTY"
};
export default CartActionTypes;
